runtime: java11

env_variables:
  RELEASE_VERSION: "6.6.3"

entrypoint: 'java "-Dio.netty.tryReflectionSetAccessible=true" --illegal-access=warn --add-opens java.base/jdk.internal.misc=ALL-UNNAMED --add-exports java.base/jdk.internal.misc=ALL-UNNAMED  -jar app-shadow.jar'